name: Build and upload preview slides for PRs in HTML and PDF

# Controls when the action will run. Triggers the workflow on pull_requests to the dev branch
on:
  pull_request:
    branches:
      - dev
jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Get the branch name to append to the resulting artifact name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Install marp
        run: npm install -g @marp-team/marp-cli@1.4.0

      - name: Build HTML slides
        run: marp README.md  --allow-local-files

      - name: Build PDF slides
        run: marp README.md --pdf --allow-local-files

      # Upload the artifact containing the preview slides. For information on
      # how download the artifact, see
      # https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts
      - name: Upload slides
        uses: actions/upload-artifact@v2
        with:
          name: slides-preview-${{ env.BRANCH_NAME }}
          path: |
            README.html
            README.pdf
